"""
Script to check SharePoint links using Selenium for Edge browser automation.
    - Supports input from Excel or simple text file
    - Outputs results as Excel or CSV/TSV.
    - Initially generated by Copilot 17-07-2026, updated 22-07-2026.
"""
import os
import pandas as pd
import tempfile
import time
import enum
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException


# Configuration
INPUT_FILE = "in.txt"
OUTPUT_FILE = r"out\out.tsv"
LINK_COLUMN_NAME = "GeneratedLink"
LONG_TIMEOUT_SECONDS = 6
TIMEOUT_SECONDS = 3
RUN_HEADLESS = False  # Currently headless mode causes login issues


# 1 - Prepare and load input data
df = pd.DataFrame()
num_links = 0
dir_path = os.path.dirname(os.path.realpath(__file__))
if INPUT_FILE.endswith(".xlsx"):
    xlsx_path = os.path.join(dir_path, INPUT_FILE)
    df = pd.read_excel(xlsx_path)
    empty_rows = df[df[LINK_COLUMN_NAME].isna()]  # Drop empty rows without a URL
    df.drop(empty_rows.index, inplace=True)
    num_links = len(df)
elif INPUT_FILE.endswith(".txt"):  # Should be a plain text file with one URL per line
    with open(os.path.join(dir_path, INPUT_FILE), "r") as f:
        data = f.read().splitlines()
    links = [link for link in data if link.strip()][1:]  # Skips header (first line)
    df = pd.DataFrame(links, columns=[LINK_COLUMN_NAME])
    df['Project Number'] = ""  # Add a placeholder column for Project Number
    num_links = len(links)
else:
    raise ValueError("Unsupported input file format. Please provide a .xlsx or .txt file.")

if num_links == 0:
    print(f"No valid rows found in '{INPUT_FILE}'. Exiting.")
    exit(0)
print(f"Loaded {num_links} rows from '{INPUT_FILE}'")


# 2 - Start Selenium WebDriver for Edge, using a temporary profile to avoid crashes
options = webdriver.EdgeOptions()
temp_edge_profile = tempfile.mkdtemp(prefix="edge-selenium-")
options.add_argument(f"--user-data-dir={temp_edge_profile}")
options.add_argument("--log-level=3")  # Reduce logging noise
options.add_experimental_option('excludeSwitches', ['enable-logging'])
if RUN_HEADLESS:
    options.add_argument("--headless=new")
driver = webdriver.Edge(options=options)


# 3 - Iterate through each row, check the link, and record the status
start = time.perf_counter()
signed_in = False
exit_error = False
results = []
num_accessible_links = 0

class LinkStatus(enum.Enum):
    ACCESSIBLE = "ACCESSIBLE"
    ACCESS_DENIED = "ACCESS DENIED"
    NOT_FOUND = "404 NOT FOUND"
    EMPTY = "EMPTY URL"
    INVALID = "NOT A SHAREPOINT SITE"
    UNKNOWN = "UNKNOWN"

def progress(results, i, project_number, url, status):
    # Wrapper function for appending to results and print progress messages
    if status == LinkStatus.ACCESSIBLE:
        global num_accessible_links
        num_accessible_links += 1
    results.append(
        {
            "Project Number": project_number,
            "Status": status.value,
            "URL": url
        }
    )
    if project_number == "":
        print(f"\t{i}/{num_links}\t{status.value} - {url}")
    else:
        print(f"\t{i}/{num_links}\t{status.value} - {project_number}")

try:
    i = 0
    for _, row in df.iterrows():
        project_number = row["Project Number"]
        url = row[LINK_COLUMN_NAME]
        i += 1
        if pd.isna(url):
            # This should not happen since we dropped empty rows, but just in case.
            progress(results, i, project_number, url, LinkStatus.EMPTY)
            continue
        if "/sites/" not in url:
            progress(results, i, project_number, url, LinkStatus.INVALID)
            continue

        driver.get(url)
        if not signed_in:
            button = WebDriverWait(driver, LONG_TIMEOUT_SECONDS).until(
                EC.presence_of_element_located((By.XPATH, "//small[contains(text(), 'Allan.Wu@riotinto.com')]"))
            )
            button.click()
            signed_in = True

        # Wait for app shell to appear; continue after TIMEOUT_SECONDS if it does not.
        try:
            WebDriverWait(driver, TIMEOUT_SECONDS).until(
                EC.presence_of_element_located((By.ID, "sp-appBar"))
            )
            progress(results, i, project_number, url, LinkStatus.ACCESSIBLE)
            continue
        except TimeoutException:
            pass

        page_text = driver.page_source.upper()
        if "ACCESS" in page_text:
            status = LinkStatus.ACCESS_DENIED
        elif (
            "ITEM DOES NOT EXIST" in page_text
            or "NOT FOUND" in page_text
            or "404" in page_text
        ):
            status = LinkStatus.NOT_FOUND
        else:
            status = LinkStatus.UNKNOWN

        progress(results, i, project_number, url, status)
    
    try:
        output_path = os.path.join(dir_path, OUTPUT_FILE)
        output_dir = os.path.dirname(output_path)
        if output_dir and not os.path.exists(output_dir):
            os.makedirs(output_dir)
        if OUTPUT_FILE.endswith(".xlsx"):
            pd.DataFrame(results).to_excel(
                output_path,
                index=False
            )
        else:
            pd.DataFrame(results).to_csv(
                output_path,
                sep='\t',
                index=False
            )
        print(f"Results written to '{OUTPUT_FILE}'")
    except Exception as e:
        print(f"Error writing to output file '{OUTPUT_FILE}': {str(e)}")
except KeyboardInterrupt:
    print("Process interrupted by user")
    exit_error = True
except Exception as e:
    print(f"Unexpected error: {str(e)}")
    exit_error = True
finally:  # Clean up and report elapsed time
    if driver:
        driver.quit()  # Bug: browser will not close when user triggers keyboard interrupt, but this is a low priority issue.
    end = time.perf_counter()
    if exit_error:
        print("Exited early due to error")
    if num_accessible_links < num_links:
        print(f"Found {num_links - num_accessible_links:d} inaccessible links")
    else:
        print(f"All links accessible")
    print(f"Elapsed time: {end - start:.2f} seconds")